### ISSUE TITLE
Take negative numbers into account

### ISSUE THREAD

**Issue by oscargus** [dragazo/numeric-sort#1]
It seems like negative numbers, i.e., the minus sign, is not taken into account. We use this crate in a project and just got a bug report: https://gitlab.com/surfer-project/surfer/-/issues/330

Now, based on the introductory example of this crate, `test-7` and so on, this may be a bit of a problem, but I guess that it in many other cases makes sense. Maybe a feasible rule to when to interpret - as minus is not having a letter directly in front of it?

**Comment by dragazo** [comment]
Huh... Yeah that is kind of tricky to define. The letter in front approach would fix this specific issue, but might be too specific. I guess there's kind of a more general issue that something like `test-7` could be interpreted either way.

Maybe [`char::is_ascii_punctuation`](https://doc.rust-lang.org/std/primitive.char.html#method.is_ascii_punctuation) might be better. It includes `[`, so it should fix your problem (if I'm understanding the issue you linked). One weird thing is that it also includes characters like `-`, so `test--7` would be interpreted as `-7`. But maybe that makes sense given that I wanted `test-7` to be interpreted as `7`. Basically the idea is that text is greedy but any punctuation character can separate a number to bypass greedily taking the `-` (or `+`, which we should probably also support).

**Comment by dragazo** [comment]
I just added basic support for negative numbers (not published yet). The only thing remaining to fix this issue would be changing the segmenter logic. Let me know if the above idea would work for you (or if you have any different ideas), and I can add it in.

**Comment by oscargus** [comment]
Thanks! Yes, for my specific use case, all(?) negative numbers will be within [], so `is_ascii_punctuation` should work well.

**Comment by dragazo** [comment]
Alright, I just updated the segmenter and published version `0.1.2`. Thanks for helping improve this lib!

**Comment by oscargus** [comment]
Thanks!
